from django.db.models import TextChoices


class ErrorMessages(TextChoices):
    internal_server_error = "Internal Server Error"
    bad_request = "Bad Request"
    resource_not_found = "Resource Not Found"
    permission_denied = "You do not have the permission to perform this action."
    access_denied = "Access Denied."
    too_many_requests = "Permission denied. Too many requests."
    unprocessable_entity = "Unprocessable Entity"
    inactive_account = "Your account is inactive. Contact your administrator."
    insecure_password = ("Insecure password! Must contain minimum of 12 characters, an uppercase, a lowercase, "
                         "a number, and a symbol")
    email_already_exist = "Account with email already exists."
    phone_already_exist = "Account with phone number already exists."
    username_already_exists = "Username already exists."
    user_email_already_verified = "Account email already verified."
    invalid_email = "Invalid Email."
    too_many_attempts_account_blocked = "Too many attempts. Account blocked"
    invalid_credentials = "Invalid Login Details."
    incorrect_password = "Incorrect password."
    invalid_token_retry_login = "The token is invalid or expired. Please login again."
    user_not_recognized = "User not recognized"
    invalid_or_expired_otp = "Invalid/Expired OTP."
    too_many_failed_otp_verification_attempts = "Too many failed OTP attempts. Request a new OTP."
    otp_already_verified = "OTP already verified."
    invalid_file = "A valid file is required"
    invalid_file_extension = "File extension not supported"
    file_too_large = "File too large"
    invalid_action = "Invalid action."
    invalid_input = "Invalid input."
    verification_unsuccessful = "Email Verification Unsuccessful. The token is invalid or expired. ❌"
    media_type_not_found = "Media Type not found."
    media_not_found = "Media not found."
    token_expired = "Not Authorized. Expired Token."
    invalid_issuer = "Invalid issuer."
    user_with_id_not_found = "User with id '{}' not found."
    invalid_user_id = "Invalid user id."
    invalid_token = "Invalid token."
    possible_duplicate_error = "Possible duplicate error."
    user_with_phone_number_not_found = "User with phone number '{}' not found."
    invalid_option = "Invalid option."
    role_already_exists = "Role '{}' already exists."
    invalid_user_type = "Invalid user type."
    role_not_found = "Role not found."
    country_not_found = "Country not found."
    role_is_required = "Role is required."
    no_permission_to_assign_role = "You do not have the permission to act on the role '{}'."
    invalid_phone_number = "Invalid phone number."
    action_failed = "Action failed."
    unknown_media_user = "Unknown media user."
    email_and_role_required = "Email and role required."
    not_a_number = "{name} is not a number."
    validation_error = "Validation error."


class ResponseMessages(TextChoices):
    # General
    login_successful = "Login Successful"
    successful_password_change = "Password changed successfully."
    user_created_successfully = "User created successfully."
    user_updated_successfully = "User updated successfully."
    otp_sent_to_email = "An OTP has been sent to your email address."
    valid_otp = "Valid OTP."
    update_successful = "Update Successful."
    verification_successful = "Email Verification Successful. ✅"
    media_deleted_successfully = "Media deleted successfully."
    account_deleted_successfully = "Account deleted successfully."
    message_received_successfully = "Message received successfully."
    phone_number_is_required = "Phone number is required."
    record_fetched_successfully = "Record(s) fetched successfully."
    profile_updated_successfully = "Profile updated successfully."
    user_acted_on_successfully = "User {} successfully."
    submitted_successfully = "Submitted successfully."
    deleted_successfully = "Deleted successfully."
    created_successfully = "Created successfully."
    access_granted = "Access granted."
    all_is_well = "All is well that ends well."


class CeleryTaskQueue(TextChoices):
    notification = "notification"
    logging = "logging"
    default = "default"


class ActivityType(TextChoices):
    delete = "delete"
    update = "update"
    create = "create"
    approve = "approve"
    reject = "reject"
    revert = "revert"
    activate = "activate"
    verify = "verify"
    deactivate = "deactivate"
    application = "application"
